# Generated by Django 4.2 on 2023-06-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='Work_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
