# Generated by Django 4.2 on 2023-06-18 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.ManyToManyField(to='accounts.supervisor')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
            ],
        ),
        migrations.CreateModel(
            name='GraduatedGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('serial', models.CharField(blank=True, max_length=255)),
                ('students', models.ManyToManyField(to='accounts.student')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisor')),
            ],
        ),
    ]
