# Generated by Django 4.2 on 2023-06-19 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_groupmembership'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
