# Generated by Django 4.2 on 2023-06-21 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0004_suggestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestions',
        ),
    ]
