# Generated by Django 4.2 on 2023-06-22 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_alter_suggestions_user'),
        ('databaseApi', '0004_recommendstudentssupervisor_recommendspervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendspervisor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='recommendspervisor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recommendspervisor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='recommendspervisor',
            name='user',
        ),
        migrations.AddField(
            model_name='recommendspervisor',
            name='supervisors',
            field=models.ManyToManyField(to='accounts.supervisor'),
        ),
        migrations.AddField(
            model_name='recommendspervisor',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendstudentssupervisor',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendstudentssupervisor',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
