# Generated by Django 4.2 on 2023-06-22 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('databaseApi', '0005_remove_recommendspervisor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendstudentssupervisor',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
