# Generated by Django 4.2 on 2023-06-23 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_university'),
        ('databaseApi', '0006_alter_recommendstudentssupervisor_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectgroup',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.supervisor'),
        ),
    ]
