# Generated by Django 4.2 on 2023-06-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_university'),
        ('databaseApi', '0007_alter_projectgroup_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='project_defination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendspervisor',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.university'),
        ),
    ]
