# Generated by Django 4.2 on 2023-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApi', '0008_alter_projectdetails_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendspervisor',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
