# Generated by Django 4.2 on 2023-06-23 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApi', '0009_alter_recommendspervisor_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSuperVisorWanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=9)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseApi.projectgroup')),
            ],
        ),
    ]
